---
- hosts: localhost
  connection: local
  gather_facts: false

  # run:
  # $ export DO_API_TOKEN=your-token
  # then run this playbook to create droplet
  tasks:
    - digital_ocean_droplet:
        unique_name: yes # "yes" makes it idempotent
        region: ams3 # slug of the region you would like your server to be created in.
        #image: ubuntu-18-10-x64 # slug of the image you would like the droplet created with.
        image: ubuntu-16-04-x64
        #ssh_key_ids: b7:eb:df:e7:9c:0c:45:b6:0a:8e:4e:cf:5f:df:e7:01
        wait: yes
        name: "tws002" # name of the droplet
        size_id: s-1vcpu-1gb # slug of the size you would like the droplet created with.
        state: present
        oauth_token: 4d00b6d30e45999197689883042a5a8c6547aaae767c9b21db5430008470d9bb
        ssh_keys: ['a7:9f:76:ac:23:14:a6:b9:ec:01:68:57:c3:50:a4:1a']
        #ssh_keys: [ 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNSZmBvvPH77jBDxkhiZCI3OfElR+frOjMKsLRbWuJwJpJqjJmQR9umimSlqOYuO2V9k5txyvMlmnG000eqCL2MFYshm5OjC33Yfnz4/UnCAI8cjQs3gcqmoyBaJlyQly8U3T5wgV4BC7k1dHBX0+7iXr8YgrPT6xbpMsUBQ4ozMXoYinQhUP+Bt2MmKcuGAEOJH3TeE9WQr3/GmcULtZONHtIS6jvrMqp7O4ycRRLycxSTmYPtnIE1PMKd5HRWvNIXEMkZkHjm/OH08sQ5aMo54a/yYrNBi7BiT7EMGWCSSXFvtVl6xyGObMMZlTHy7SF8fgANiLlXUiAEHzppewV root@jenkins-ansible' ] # <----- put your numeric SSH key in here
      register: created_droplet

    - digital_ocean_tag:
        name: some-sample-tag 
        resource_id: "{{ created_droplet.data.droplet.id }}"
        state: present
      register: tag_response

    - name: add hosts
      add_host:
        name: "{{ created_droplet.data.ip_address }}"
        groups: "do"
